---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment 
summary: BlueXPでAzure BLOBストレージアカウントを検出したら、NetAppデータサービスを使用してバックアップ、階層化、データ同期を実行できます。 
---
= Azure BLOBストレージでNetAppデータサービスを使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPでAzure BLOBストレージアカウントを検出したら、NetAppデータサービスを使用してバックアップ、階層化、データ同期を実行できます。

* BlueXPのバックアップとリカバリ*を使用して、オンプレミスのONTAPシステムやCloud Volumes ONTAPシステムからAzure Blobストレージにデータをバックアップできます。
+
作業を開始するには、キャンバスに移動し、オンプレミスのONTAPまたはCloud Volumes ONTAP作業環境をAzure Blob Storage作業環境にドラッグアンドドロップします。

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Azure BlobストレージへのONTAPデータのバックアップの詳細については、こちらをご覧ください"^]。

* BlueXP階層化*を使用して、アクセス頻度の低いデータをオンプレミスのONTAPクラスタからAzure BLOBストレージに階層化できます。
+
作業を開始するには、キャンバスに移動し、オンプレミスのONTAP作業環境をAzure Blob Storage作業環境にドラッグアンドドロップします。

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-azure.html["ONTAPデータをAzure BLOBストレージに階層化する方法については、こちらをご覧ください"^]。

* BlueXPのコピーと同期*を使用して、Azure BLOBストレージアカウントとの間でデータを同期します。
+
作業を開始するには、Canvasに移動し、ソースの作業環境をターゲットの作業環境にドラッグアンドドロップします。Azure Blob Storageの作業環境は、ソースでもターゲットでもかまいません。

+
Azure Blob Storage作業環境を選択し、[サービス]パネルの*[コピーと同期]*をクリックして、Azure Blob Storageアカウントとの間でデータを同期することもできます。

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["BlueXPのコピーと同期サービスの詳細については、こちらをご覧ください"^]。


